"""
app.py
Streamlit dashboard for the SIMULATED campaign dataset.

Run:  streamlit run app.py

Flow: sidebar filters -> SQL query pulls matching rows from SQLite ->
      metrics.py computes KPIs -> Plotly draws the charts -> ai_insights.py writes the text.
"""
import pandas as pd
import plotly.graph_objects as go
import streamlit as st

import ai_insights
import metrics
import sql_analysis

st.set_page_config(page_title="Campaign Performance (simulated data)", layout="wide")

STATUS_COLORS = {"Scale": "#1a9850", "Watch": "#e6a700", "Fix": "#d73027"}
SPEND_COLOR, REVENUE_COLOR = "#7a8799", "#1f6feb"


def inr(value: float) -> str:
    """Format rupees in lakhs when large (1 lakh = 100,000)."""
    if pd.isna(value):
        return "–"
    return f"₹{value / 1e5:.2f}L" if value >= 1e5 else f"₹{value:,.0f}"


@st.cache_data
def filter_options():
    channels = sql_analysis.run_query("SELECT DISTINCT channel FROM campaigns ORDER BY channel")["channel"].tolist()
    dates = sql_analysis.run_query("SELECT MIN(date) AS first, MAX(date) AS last FROM campaigns").iloc[0]
    return channels, pd.to_datetime(dates["first"]).date(), pd.to_datetime(dates["last"]).date()


@st.cache_data
def load_rows(channels: tuple, start: str, end: str) -> pd.DataFrame:
    placeholders = ",".join("?" * len(channels))        # one "?" per selected channel
    sql = f"SELECT * FROM campaigns WHERE date BETWEEN ? AND ? AND channel IN ({placeholders})"
    return sql_analysis.run_query(sql, (start, end, *channels))


# ---------------- Header and filters ----------------
st.title("Campaign Performance Dashboard")
st.warning("**Simulated data.** Every number here is generated by `generate_data.py`. "
           "This is a portfolio project, not a real ad account.", icon="⚠️")

all_channels, first_day, last_day = filter_options()
with st.sidebar:
    st.header("Filters")
    channels = st.multiselect("Channel", all_channels, default=all_channels)
    picked = st.date_input("Date range", (first_day, last_day), min_value=first_day, max_value=last_day)

if not channels or len(picked) != 2:
    st.info("Pick at least one channel and a start and end date.")
    st.stop()

df = load_rows(tuple(channels), str(picked[0]), str(picked[1]))
if df.empty:
    st.info("No rows match these filters.")
    st.stop()

# ---------------- KPI cards ----------------
t = metrics.totals(df)
cards = st.columns(6)
cards[0].metric("Spend", inr(t.spend))
cards[1].metric("Revenue", inr(t.revenue))
cards[2].metric("ROAS", f"{t.roas:.2f}×", help="Revenue ÷ spend. Rupees back for each rupee of ad spend.")
cards[3].metric("Conversions", f"{t.conversions:,.0f}")
cards[4].metric("CPA", inr(t.cpa), help="Spend ÷ conversions. Cost of one conversion.")
cards[5].metric("CTR", f"{t.ctr:.2%}", help="Clicks ÷ impressions. Share of views that clicked.")

campaigns = metrics.campaign_table(df)

# ---------------- Charts row 1 ----------------
left, right = st.columns(2)

with left:
    st.subheader("Weekly spend vs revenue")
    weekly = metrics.summarise(df, ["week_start"])
    fig = go.Figure()
    fig.add_bar(x=weekly["week_start"], y=weekly["spend"], name="Spend", marker_color=SPEND_COLOR)
    fig.add_bar(x=weekly["week_start"], y=weekly["revenue"], name="Revenue", marker_color=REVENUE_COLOR)
    fig.update_layout(barmode="group", yaxis_title="INR", xaxis_title="Week starting",
                      legend=dict(orientation="h", y=1.12), margin=dict(t=30, b=10), height=380)
    st.plotly_chart(fig, width="stretch", config={"displayModeBar": False})

with right:
    st.subheader("ROAS by campaign")
    ordered = campaigns.sort_values("roas")              # best at the top of a horizontal bar chart
    fig = go.Figure(go.Bar(
        x=ordered["roas"], orientation="h",
        y=[f"{c}  {r:.2f}×" for c, r in zip(ordered["campaign"], ordered["roas"])],
        marker_color=ordered["status"].map(STATUS_COLORS),
        customdata=ordered["status"], hovertemplate="%{y}<br>%{customdata}<extra></extra>"))
    fig.add_vline(x=metrics.BREAK_EVEN_ROAS, line_dash="dash", line_color="#d73027",
                  annotation=dict(text="1× break-even", y=1.09, yref="paper", showarrow=False, xanchor="right"))
    fig.add_vline(x=metrics.TARGET_ROAS, line_dash="dash", line_color="#1a9850",
                  annotation=dict(text="3× benchmark", y=1.09, yref="paper", showarrow=False, xanchor="left"))
    fig.update_layout(xaxis_title="ROAS (revenue ÷ spend)", margin=dict(t=45, b=10), height=380,
                      xaxis_range=[0, max(ordered["roas"].max() * 1.1, 3.5)])
    st.plotly_chart(fig, width="stretch", config={"displayModeBar": False})
    st.caption("Green = Scale, amber = Watch, red = Fix.")

# ---------------- Charts row 2 ----------------
left, right = st.columns(2)

with left:
    st.subheader("Funnel")
    fig = go.Figure(go.Funnel(
        y=["Impressions", "Clicks", "Conversions"],
        x=[t.impressions, t.clicks, t.conversions],
        text=[f"{t.impressions:,.0f}",
              f"{t.clicks:,.0f}  (CTR {t.ctr:.2%})",
              f"{t.conversions:,.0f}  (conv. rate {t.cvr:.2%})"],
        textinfo="text", textposition=["inside", "outside", "outside"], marker_color=REVENUE_COLOR))
    # Log scale: each step is ~1-3% of the one before, so on a normal scale
    # clicks and conversions would be invisible slivers.
    fig.update_layout(xaxis_type="log", margin=dict(t=10, b=10), height=340)
    st.plotly_chart(fig, width="stretch", config={"displayModeBar": False})
    st.caption("Bar widths use a log scale so the small steps stay visible. "
               "CTR = clicks ÷ impressions. Conversion rate = conversions ÷ clicks.")

with right:
    st.subheader("Weekly cost per click by campaign")
    cpc = metrics.summarise(df, ["campaign", "week_start"])
    fig = go.Figure()
    for name, part in cpc.groupby("campaign"):
        first = part["cpc"].iloc[0]
        fig.add_scatter(x=part["week_start"], y=part["cpc"] / first * 100, name=name, mode="lines+markers")
    fig.add_hline(y=100, line_dash="dot", line_color="#999")
    fig.update_layout(yaxis_title="CPC index (first week = 100)", xaxis_title="Week starting",
                      legend=dict(orientation="h", y=-0.3), margin=dict(t=10, b=10), height=340)
    st.plotly_chart(fig, width="stretch", config={"displayModeBar": False})
    st.caption("CPC = spend ÷ clicks. Indexed so campaigns with very different CPCs can share one chart. "
               "A line climbing above 100 means clicks are getting more expensive.")

# ---------------- Campaign table ----------------
st.subheader("Campaigns")
st.caption("Click a column header to sort. Status: **Scale** = ROAS ≥ 3×, **Fix** = ROAS < 1×, **Watch** = in between.")
table = campaigns[["campaign", "channel", "status", "spend", "spend_share", "revenue",
                   "roas", "conversions", "cpa", "cpc", "ctr", "cvr"]].copy()
for col in ["spend_share", "ctr", "cvr"]:
    table[col] *= 100                                   # show as percentages
table[["spend", "revenue", "cpa"]] = table[["spend", "revenue", "cpa"]].round(0)
st.dataframe(
    table.style.map(lambda s: f"color: {STATUS_COLORS[s]}; font-weight: 600", subset=["status"]),
    hide_index=True, width="stretch",
    column_config={
        "campaign": "Campaign", "channel": "Channel", "status": "Status",
        "spend": st.column_config.NumberColumn("Spend (₹)", format="localized"),
        "spend_share": st.column_config.NumberColumn("Spend share", format="%.1f%%"),
        "revenue": st.column_config.NumberColumn("Revenue (₹)", format="localized"),
        "roas": st.column_config.NumberColumn("ROAS", format="%.2f×"),
        "conversions": st.column_config.NumberColumn("Conversions", format="%d"),
        "cpa": st.column_config.NumberColumn("CPA (₹)", format="localized"),
        "cpc": st.column_config.NumberColumn("CPC (₹)", format="%.1f"),
        "ctr": st.column_config.NumberColumn("CTR", format="%.2f%%"),
        "cvr": st.column_config.NumberColumn("Conv. rate", format="%.2f%%"),
    })

# ---------------- AI panel ----------------
st.subheader("AI insights")
backend = ai_insights.provider()
if backend == "rules":
    st.info("No API key found, so this panel is using the free **rule-based fallback** (plain Python, not AI). "
            "Set `ANTHROPIC_API_KEY` or `OPENAI_API_KEY` and restart to use an LLM.")
else:
    st.caption(f"Using **{backend}**. The model only sees a summary table of the filtered data above, "
               "and is told to answer from that alone. It can still make mistakes, so check its numbers.")

left, right = st.columns(2)
with left:
    if st.button("Generate summary and budget recommendation"):
        try:
            with st.spinner("Writing..."):
                st.session_state["summary"] = ai_insights.generate_summary(df)
        except Exception as error:                      # bad key, no credit, no network...
            st.session_state["summary"] = f"LLM call failed: {error}"
    if "summary" in st.session_state:
        st.write(st.session_state["summary"])

with right:
    with st.form("question"):
        question = st.text_input("Ask about this data", placeholder="Which campaign should I cut?")
        asked = st.form_submit_button("Ask")
    if asked and question.strip():
        try:
            with st.spinner("Thinking..."):
                st.session_state["answer"] = ai_insights.answer_question(df, question)
        except Exception as error:
            st.session_state["answer"] = f"LLM call failed: {error}"
    if "answer" in st.session_state:
        st.write(st.session_state["answer"])

with st.expander("What the AI is given (the full prompt data)"):
    st.code(ai_insights.build_context(df))

# ---------------- SQL queries ----------------
with st.expander("SQL queries (run on the full dataset, ignoring filters)"):
    for title, sql in sql_analysis.QUERIES.items():
        st.markdown(f"**{title}**")
        st.code(sql.strip("\n"), language="sql")
        st.dataframe(sql_analysis.run_query(sql), hide_index=True)
